services:
  mysql:
    image: mysql:8.0-bookworm
    container_name: mysql
    command: ["mysqld","--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - determinacao_data:/var/lib/mysql
      - ./backup:/backup
    ports:
      - 3306:3306
    restart: unless-stopped

volumes:
  determinacao_data:
    external: true
